export const ALARM_SOUNDS = [
  { id: "default", name: "標準", path: "path/to/alarm.mp3" },
  // { id: "bell", name: "ベル", path: "path/to/bell.mp3" },
  // { id: "pigeon", name: "ハト", path: "path/to/pigeon.mp3" },
  { id: "bellding", name: "ベル", path: "path/to/bellding.mp3" },
  // { id: "coin", name: "コイン", path: "path/to/coin.mp3" },
  // { id: "dog-bark", name: "犬", path: "path/to/dog-bark-1.mp3" },
  // { id: "cat-meow", name: "猫", path: "path/to/cat-meow-1.mp3" },
  { id: "notification", name: "通知1", path: "path/to/notification-18.mp3" },
  { id: "notification2", name: "通知2", path: "path/to/notification-22.mp3" },
  { id: "tone1", name: "トーン1", path: "path/to/tone1.mp3" },
  { id: "tone2", name: "トーン2", path: "path/to/tone2.mp3" },
  { id: "tone3", name: "トーン3", path: "path/to/tone3.mp3" },
  { id: "tone4", name: "トーン4", path: "path/to/tone4.mp3" },
];
